version: '3.8'

services:
  scraper-api:
    build: .
    container_name: portal-vagas-scraper
    ports:
      - "8082:8082"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - CHROME_HEADLESS=true
      - API_PORT=8082
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    depends_on:
      - chrome
    networks:
      - portal-vagas-network

  chrome:
    image: selenium/standalone-chrome:latest
    container_name: selenium-chrome
    ports:
      - "4444:4444"
    environment:
      - SE_NODE_MAX_SESSIONS=3
      - SE_NODE_SESSION_TIMEOUT=300
    shm_size: 2gb
    networks:
      - portal-vagas-network

  scheduler:
    build: .
    container_name: scraper-scheduler
    command: python scheduler.py
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    volumes:
      - ./logs:/app/logs
    depends_on:
      - scraper-api
    networks:
      - portal-vagas-network

networks:
  portal-vagas-network:
    driver: bridge